### ISSUE TITLE
FR: Move DiceBear icon/avatar retrieval from server-side to client-side

### ISSUE THREAD

**Issue by xinbenlv** [google/wikiloop-doublecheck#168]

**Comment by flogado** [comment]
But why?

**Comment by FlorianKoerner** [comment]
But why?

**Comment by xinbenlv** [comment]
@FlorianKoerner this issue is a follow up Action Item in #165 

> Why do you create the avatars on the server side and not in the browser? The page loads very slowly.
> If you want to use the HTTP-API of DiceBear, you don't have to worry about the latency. DiceBear is powered by the worker infrastructure of Cloudflare.
> https://codepen.io/FlorianKoerner/pen/mdyzNjK

Do I understand your suggestion correctly?

**Comment by FlorianKoerner** [comment]
Is it currently not server-side? I thought so.

It is better to create the avatars client-side.

But the title here says to create it server-side in the future. I just wouldn't do that.

**Comment by xinbenlv** [comment]
Sorry, I think for some crazy reason I totally swap what I intend to do. I want to take your suggest and let the client-side retrieve it instead of server side do it.....

Thank you for following up on this repo, Florian
