### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by WyattSmith101** [google/wikiloop-doublecheck#386]
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail
![Screenshot 2021-01-14 at 18 57 20](https://user-images.githubusercontent.com/77455316/104622852-6f77b300-569a-11eb-800d-f758038c55a6.png)

**Comment by xinbenlv** [comment]
I think it's resolved now.
